project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs

website:
  title: "Yuki MATSUDA"
  favicon: images/favicon.png
  bread-crumbs: false
  sidebar:
    title: <img src="/images/favicon.png" height="28" vertical-align="text-bottom">
           Yuki MATSUDA
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - text: "HOME"
        file: index.qmd
      - text: "---"
      - text: "スライド"
        file: slides/index.qmd
      - text: "---"
      - section: "Bioinformatics"
        contents: bio/*.qmd
      - text: "---"
      - section: "Command Line Tools"
        contents: cli/*.qmd
      - text: "---"
      - section: "Python"
        contents: python/*.qmd
      - text: "---"
      - section: "Windows"
        contents: win/*.qmd
      - text: "---"
      - section: "Web 開発"
        contents: site/*.qmd
  page-footer:
    right: "Copyright 2023 &ndash; 2024, Yuki Matsuda"
  google-analytics: "G-HLCP5V0Y7N"

format:
  html:
    theme: static/custom.scss
    fontsize: 16px
    grid:
      sidebar-width: 270px
      body-width: 810px
      margin-width: 0px
    toc: false
    toc-location: body
    toc-title: "Table Of Contents:"
    link-external-icon: false
    link-external-newwindow: true
    code-copy: false
    highlight-style: github
    template-partials:
      - static/title-block.html
    html-math-method: katex
  revealjs:
    theme: static/slide.scss
    width: 1080
    height: 810
    margin: 0
    scrollable: true
    history: false
    slide-number: c/t
    code-line-numbers: false
    auto-stretch: false
