baseURL = 'http://yukimatsuda1999.github.io/'
languageCode = 'ja-jp'
title = 'Notemy - A Website for Personal Documentation'

theme = 'hugo-theme-mindoc'

copyright = "(É”) 2022 Yuki Matsuda"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

	[markup.highlight]
		noClasses=false
