baseURL = 'http://ymat2.github.io/'
languageCode = 'ja-jp'
title = 'Yuki Matsuda'
theme = 'hugo-theme-mindoc'
copyright = "(É”) 2022 Yuki Matsuda"
uglyURLs = true
enableEmoji = true

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

	[markup.highlight]
		noClasses=false
