---
format:
  html:
    title: "nano"
    subtitle: "small で friendly なテキストエディタ"
---

- 公式: <https://www.nano-editor.org/>
- マニュアル: <https://www.nano-editor.org/dist/latest/nano.html>


## Install

もともと入っているものを使うか、`brew` や `apt` でインストールする。

```sh
which -a nano

brew install nano  ## mac
sudo apt install nano  ## ubuntu
```

macOS 12.3 Monterey 以降、
Mac の `nano` の正体は `pico` なので、
いろいろ設定して使いたい場合は `brew` でインストールする。


## Usage

```sh
## 新規作成
nano

## 既存のファイルを編集
nano hoge.txt
```

### Keyboard shortcuts

デフォルトで編集画面の下部に書いてある。
表は編集画面でのショートカット。
nano のバージョンによって異なるものもあるっぽい。

|Key|コマンド|操作|
|:---|:---|:---|
|<kbd>control</kbd><kbd>G</kbd>|Help|ヘルプ画面へ|
|<kbd>control</kbd><kbd>X</kbd>|Exit|編集画面を抜ける|
|<kbd>control</kbd><kbd>O</kbd>|Write Out|ファイル名を指定して書き込み|
|<kbd>control</kbd><kbd>R</kbd>|Read File|ファイル名を指定して読み込み|
|<kbd>control</kbd><kbd>W</kbd>|Where Is|ファイル内検索|
|<kbd>control</kbd><kbd>\ </kbd>|Replace|ファイル内置換|
|<kbd>control</kbd><kbd>K</kbd>|Cut|選択範囲を切り取り|
|<kbd>control</kbd><kbd>U</kbd>|Paste|カーソル位置に文字列を貼り付け|
|<kbd>control</kbd><kbd>T</kbd>|Execute|コマンドラインの操作を実行して出力を貼り付け|
|<kbd>control</kbd><kbd>J</kbd>|Justify|均等割付|
|<kbd>control</kbd><kbd>C</kbd>|Location|カーソル位置の表示|
|<kbd>control</kbd><kbd>/</kbd>|Go To Line|行数を指定してジャンプ|
|<kbd>control</kbd><kbd>]</kbd>|Complete|ファイル中にあるほかの単語を探して補完|
|<kbd>Meta</kbd><kbd>U</kbd>|Undo|ひとつ前の状態に戻す|
|<kbd>Meta</kbd><kbd>E</kbd>|Redo|同じ操作をおこなう|
|<kbd>Meta</kbd><kbd>A</kbd>|Set Marl|選択範囲の開始点をセット|
|<kbd>Meta</kbd><kbd>6</kbd>|Copy|選択範囲をコピー|
: {tbl-colwidths="[20, 20, 60]"}

Meta キーは Windows なら <kbd>alt</kbd>、Macなら <kbd>esc</kbd>


## Configuration

基本的な設定は[コマンドラインオプション][cmd]で指定することもできるが、
一時的な設定でなければ config ファイルに書いてしまった方が楽。

[cmd]: https://www.nano-editor.org/dist/latest/nano.html#Nanorc-Files:~:text=6%20Command%2Dline%20Options

読み込まれる順番は、まず `/etc/nanorc` 、次に `~/.nanorc` または `~/.config/nano/nanorc`。

Linux では `/etc/nanorc` や `/usr/share/doc/nano/examples/samples.nanorc` に、
Mac に brew で入れた場合は `/usr/local/Cellar/nano/%v/share/doc/nano/sample.nanorc`
にドキュメントとコマンドがコメントアウトされて書いてあるので、
これを `~/.nanorc` または `~/.config/nano/nanorc` にコピーして編集する。(`%v` は `nano` のバージョン)

自分で書いてしまってもいい。たとえば:

```{.sh filename="nanorc"}
set autoindent    # 改行時にインデントを揃える
set nowrap	      # 横に長い行を勝手に改行しない
set smooth	      # スクロールがスムーズに（あんまり実感したことはない）
set tabsize 4	    # タブサイズ（スペースの数）の設定
set mouse	        # マウスを使えるようにする
```

`set mouse` の挙動について
:	設定しなくても一応使える。
  普通に文章を選択して <kbd>Ctrl</kbd><kbd>C</kbd> したり
  <kbd>Ctrl</kbd><kbd>V</kbd> したり。
  ただカーソルは動かせないっぽい。

:	`set mouse` すると完全に `nano` の中の挙動になる。
  カーソルも動く。
  ダブルクリックで範囲選択開始 (`Set Mark`)、次のクリックで範囲決定。
  もう一度クリックすると解除 (`Unset Mark`)。

### Syntax highlight

デフォルトの見た目は非常に寂しい。

Linuxでは `/usr/share/nano/` 、Mac (brew) では `/usr/local/share/nano/` や
`/usr/local/Cellar/nano/%v/share/nano/` にハイライト定義ファイルが置いてあるので、
これらの設定を `~/.nanorc` に加える。

または野生の定義ファイルを使う手もある。(c.f. <https://github.com/scopatz/nanorc>)

```{.sh filename="nanorc"}
include "/usr/share/nano/*.nanorc"
```

### Key Bind

キーボードショートカットは変更可能。
例えば <kbd>Ctrl</kbd><kbd>Z</kbd> を `Undo` に割り当てたい場合、以下のように書く。

```{.sh filename="nanorc"}
bind ^Z undo	main
```
