---
format:
  html:
    title: "Vi/Vim"
---

<https://www.vim.org/>

vi (ヴィーアイ) は UNIX に標準搭載されているテキストエディタ。
Vim (ヴィム) は vi の発展版で、近年の UNIX 系 OS で `vi` を打って起動するのは
Vim であることが多い。


## 最低限覚えておくこと

- 起動時はノーマルモード (編集はできない)。
- カーソル移動は (矢印キーも使えるけど)
  基本 <kbd>h</kbd>: 左, <kbd>j</kbd>: 下, <kbd>k</kbd>: 上, <kbd>l</kbd>: 右 でおこなう。
- 編集は <kbd>i</kbd> でインサートモード `--INSERT--` に入って行う。
  インサートモードではカーソル移動はなるべくしない。
- インサートモードから抜けるには <kbd>esc</kbd> や <kbd>control</kbd><kbd>C</kbd>
- <kbd>:w</kbd> で変更を保存、<kbd>:q</kbd> で終了
- <kbd>:wq</kbd> や <kbd>ZZ</kbd> で保存して終了
- <kbd>:q!</kbd> で保存せずに強制終了


## 設定

ノーマルモードで `:set <option>` もしくは `~/.vimrc`

c.f. <https://github.com/ymat2/dotfiles/blob/main/.vimrc>


## `vimtutor`

`vim` の操作を習得するための練習問題付き教材。
`vimtutor` で起動する。

カーソル移動
: <kbd>h</kbd>, <kbd>j</kbd>, <kbd>k</kbd>, <kbd>l</kbd> (左、下、上、右)
: <kbd>▲</kbd>, <kbd>◀︎</kbd>, <kbd>▶︎</kbd>, <kbd>▼</kbd>

起動と終了
: <kbd>esc</kbd> でノーマルモードへ
: <kbd>:q!</kbd> で保存せずに終了
: <kbd>:w</kbd> で変更を保存、<kbd>:q</kbd> で終了
: <kbd>:wq</kbd> で保存して終了

テキストの削除
: <kbd>x</kbd> でカーソルの右側の文字を削除

テキストの挿入
: 編集箇所まで移動 (インサートモードでも移動できるけどしないつもりで)
: <kbd>I</kbd> でインサートモードへ
: 編集したら <kbd>esc</kbd> や <kbd>control</kbd><kbd>C</kbd> でノーマルモードへ

テキストの追加
: 編集行まで移動 (行の上ならどの位置でも OK)
: <kbd>A</kbd> でインサートモードへ。カーソルは末尾に移る。
: 編集したらノーマルモードへ

削除コマンド (オペレータ)
: 削除したい箇所の"先頭"にカーソルを移動
: <kbd>dw</kbd> で空白を含む単語の末尾まで
: <kbd>de</kbd> で空白を含まない単語の末尾まで
: <kbd>d$</kbd> でカーソル位置から行末まで

モーション + カウント
: <kbd>w</kbd>、<kbd>e</kbd> は単体でカーソル移動コマンドとして機能する。
: 数字と組み合わせて使用できる。
: <kbd>2w</kbd> で2単語先の語頭へ
: <kbd>3e</kbd> で3単語先の終端へ
: <kbd>0</kbd> で行頭へ

オペレータ + カウント + モーション
: <kbd>d2w</kbd> でカーソル位置から2単語削除

行の削除
: 削除する行にカーソルを移動 (位置はどこでもOK)
: <kbd>dd</kbd> で行を削除
: <kbd>2dd</kbd> で2行削除

操作のやり直し
: <kbd>u</kbd> で直前の操作を取り消し
: <kbd>U</kbd> で行全体の操作を取り消し

行の貼り付け
: <kbd>dd</kbd> で行をカット
: 貼り付けたい位置のひとつ上の行へカーソルを移動
: <kbd>p</kbd> で貼り付け

置換 (使う場面ある？後述する `s///g` で十分な気もする。)
: 置換する文字の先頭にカーソルを移動
: <kbd>r置換先の文字</kbd> で置換

変更
: <kbd>ce</kbd> でカーソル位置から単語の終わりまでを削除
: 同時にインサートモードに移るので、編集して <kbd>esc</kbd>

ファイル内の移動
: <kbd>control</kbd><kbd>G</kbd> で行番号を取得
: <kbd>G</kbd> でファイルの最下行へ
: <kbd>gg</kbd> でファイルの先頭へ
: 行番号 <kbd>G</kbd> で指定した行へ

検索
: <kbd>/</kbd> + 検索したい単語 で下方向、<kbd>?</kbd> + 検索したい単語で上方向に検索
: <kbd>n</kbd> で次のヒット、<kbd>N</kbd> で前のヒットへカーソルを移動

対応する括弧を検索
: <kbd>%</kbd> でカーソル位置の括弧と対応する括弧へ移動

置換
: <kbd>:s/old/new/g</kbd> でカーソル行の "old" を "new" に置換
: <kbd>:#,#s/old/new/g</kbd> で置換開始行と終了行を指定
: <kbd>:%s/old/new/g</kbd> でファイル全体にわたって置換
: <kbd>:%s/old/new/gc</kbd> でファイル全体にわたって1つ1つ確認をとりながら置換

外部コマンドの実行
: <kbd>:!</kbd> に続けてコマンドを実行できる。(e.x. <kbd>:!pwd</kbd>)
: Enter で終了

範囲選択
: <kbd>v</kbd> でビジュアルモードに移行
: カーソルキーを移動して範囲選択
: <kbd>shift</kbd><kbd>v</kbd> は行選択モード、<kbd>control</kbd><kbd>v</kbd> は矩形選択モード

ファイル、標準出力の取り込み
: <kbd>:r ファイル名</kbd> でファイルの内容をカーソル位置に挿入
: <kbd>:r :!pwd</kbd> などで、コマンドの標準出力を取り込むこともできる。

オープンコマンド
: <kbd>o</kbd> でカーソル位置の下に行を挿入してインサートモードへ
: <kbd>O</kbd> でカーソル位置の上に行を挿入してインサートモードへ

置換モード
: <kbd>R</kbd> で置換モードへ
: 文字を打つと元々あった文字は置き換えられる。
: <kbd>esc</kbd> や <kbd>control</kbd><kbd>C</kbd> で脱出

コピー
: <kbd>v</kbd> でビジュアルモードに移行して範囲選択 → <kbd>y</kbd> でコピー
: <kbd>p</kbd> でペースト
: <kbd>yw</kbd> で1単語コピー
: <kbd>yy</kbd> で行まるごとコピー
