---
format:
  html:
    title: "WSL"
    subtitle: "<u>W</u>indows <u>S</u>ubsystem for <u>L</u>inux"
---


<https://learn.microsoft.com/ja-jp/windows/wsl/>

Windows で Linux ディストリビューションを扱うための機能


## WSL のインストール: Windows11 の場合

参考: <https://chigusa-web.com/blog/wsl2-win11/>

### WSL のインストール

1. <kbd>Win</kbd><kbd>X</kbd> → <kbd>A</kbd> でターミナルを管理者として起動。

1. `wsl --install`

### 再起動と設定

1. マシンを再起動する。

1. 再起動後、インストール処理を経て Ubuntu が起動する。

1. `Enter new UNIX usernaem:` と表示されたらユーザーネームを設定<br>
   (NG 例: `松田` (日本語), `y matsuda` (スペース), `y.matsuda` (ピリオド))

1. `Enter new UNIX password:` と表示されたらパスワードを設定。
   `sudo` とかするときに要求される。

1. `Retype new UNIX password:` と表示されたらパスワードを再入力


## WSL のインストール: Windows10 の場合

参考: <https://lab.sonicmoov.com/development/windows-bash/>

### Windows subsystem for Linux (WSL) を有効化する

1. <kbd>Win</kbd><kbd>S</kbd> → 「コントロールパネル」を検索 → 「開く」

1. 「プログラム」を開く。

1. Windows の機能の有効化または無効化」をクリック。

1. 「Windows Subsystem for Linux」にチェック → 「OK」

1. 「今すぐ再起動(N)」

### Ubuntu のインストール

1. <kbd>Win</kbd><kbd>S</kbd> → 「Microsoft Store」を検索 → 「開く」

1. 「Ubuntu」を検索してクリック。

1. 「入手」

### Ubuntu の起動と設定

1. <kbd>Win</kbd><kbd>S</kbd> → 「Ubuntu」を検索 → 「開く」

1. `Enter new UNIX usernaem:` と表示されたらユーザーネームを設定<br>
   (NG: `松田` (日本語), `y matsuda` (スペース), `y.matsuda` (ピリオド))

1. `Enter new UNIX password:` と表示されたらパスワードを設定。
   `sudo` とかするときに要求される。

1. `Retype new UNIX password:` と表示されたらパスワードを再入力


## Ubuntu の更新・アップグレード

```sh
# 最新のパッケージ情報を取得
sudo apt update

# パッケージを最新に更新
sudo apt upgrade
```


## 余談: Windows 標準のターミナル

コマンドプロンプト
: 古の Microsoft 製 CUI

[PowerShell](https://learn.microsoft.com/ja-jp/powershell/)
: コマンドプロンプトの後継 (Windows7 以降)。
: コマンドプロンプトで使えたコマンドも基本的に使える。

Windows Terminal
: コマンドプロンプト、PowerShell、bash (WSL 経由)
  など複数のコマンドラインシェルのホストアプリケーション。
: <kbd>Win</kbd><kbd>X</kbd> → <kbd>I</kbd>/<kbd>A</kbd>(管理者として実行)
: <kbd>Ctrl</kbd><kbd>,</kbd>で設定画面。
  デフォルトのプロファイルや外観をいじれる。
